name: Deploy DEV

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: lab_5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_AUTH_TYPE: azure-cli
        run: databricks bundle validate -t dev

      - name: Deploy bundle to DEV
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_AUTH_TYPE: azure-cli
        run: databricks bundle deploy -t dev